config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "home#index"
  get "/new_user", to: "user#new"
  post "/post_user", to: "user#create"
  get "/details_user/:id", to: "user#details", as: :details_user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/usuario.rb
class Usuario < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @user = Usuario.all
  end

end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def new

  end

  def create
    user = Usuario.new(nome: params[:username], idade: params[:useridade], peso: params[:userpeso], altura: params[:useraltura], email: params[:useremail])

    if user.save
      redirect_to root_path
    else
      puts "Messagem de ERRO!"
      redirect_to root_path
    end
  end

  def details
    @user_details = Usuario.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<div class="botao">
  <%= link_to(new_user_path) do %>
    <i class="fas fa-plus-square"></i> Criar Usuário
  <% end %>
</div>

<table class="table table-hover">
  <thead >
    <tr style="background-color:#e4e2e3">
      <th> Nome </th>
      <th> E-mail </th>
      <th> Ações </th>
    </tr>
  </thead>
  <tbody>
    <% @user.each do |us| %>
      <tr>
        <td><%= us.nome %></td>
        <td><%= us.email %></td>


        <td>
          <%= link_to(details_user_path(id: us.id)) do %>
            <i class="fas fa-info-circle"></i>
          <% end %> |

          <%= link_to("/") do %>
            <i class="fas fa-edit"></i>
          <% end %> |

          <%= link_to("/") do %>
            <i class="fas fa-trash-alt"></i>
          <% end %>
        </td>


      </tr>
    <% end %>
  </tbody>

</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Banco</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/user/details.html.erb
<div class="botao">
    <%= link_to("/") do %>
      <i class="fas fa-arrow-circle-left"></i> voltar
    <% end %>
</div>
<table class="table table-hover">
  <thead>
    <tr  style="background-color:#e4e2e3">
      <th> Nome </th>
      <th>E-mail </th>
      <th>Idade</th>
      <th>altura</th>
      <th>peso</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @user_details.nome %></td>
      <td><%= @user_details.email %></td>
      <td><%= @user_details.idade %></td>
      <td><%= @user_details.altura %></td>
      <td><%= @user_details.peso %></td>
    </tr>
  </tbody>
</table>

app/views/user/new.html.erb
<div class="botao">
  <%= link_to("/") do %>
    <i class="fas fa-arrow-circle-left"></i> voltar
  <% end %>
</div>/
<center><h3> Criar Usuário</h3></center>


<div class="form">
  <%= form_tag(post_user_path, class:"tagform") do %>

    <div class="form_element"><%= text_field_tag "username", nil, class:"forminput", placeholder: "digite seu nome" %></div>
    <div class="form_element"><%= text_field_tag "useremail", nil, class:"forminput", placeholder: "digite seu e-mail" %></div>
    <div class="form_element"><%= number_field_tag "useridade", nil, class:"forminput", placeholder: "digite sua idade" %></div>
    <div class="form_element"><%= text_field_tag "useraltura", nil, class:"forminput", placeholder: "digite sua altura" %></div>
    <div class="form_element"><%= text_field_tag "userpeso", nil, class:"forminput", placeholder: "digite seu peso" %></div>

    <%= button_tag("enviar", class:"forminput") %>

  <% end %>
</div>